## ---------------------------------------------------------------------
##
## Copyright (C) 2016-17 by the krims authors
##
## This file is part of krims.
##
## krims is free software: you can redistribute it and/or modify
## it under the terms of the GNU Lesser General Public License as published
## by the Free Software Foundation, either version 3 of the License, or
## (at your option) any later version.
##
## krims is distributed in the hope that it will be useful,
## but WITHOUT ANY WARRANTY; without even the implied warranty of
## MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
## GNU Lesser General Public License for more details.
##
## You should have received a copy of the GNU Lesser General Public License
## along with krims. If not, see <http://www.gnu.org/licenses/>.
##
## ---------------------------------------------------------------------

language: cpp
sudo: required
dist: trusty

branches:
  except:
    - dev
    - /^dev-.*$/
    - /^dev_.*$/

env:
  global:
    # Use two cores for the build
    - CORES=2
    #
    # Use a known-to-work rapidcheck seed
    - RC_PARAMS="seed=16920708173099178154 verbose_progress=1 noshrink=1"

before_install:
    - pip install --user cpp-coveralls

addons:
  apt:
    sources:
      # Repo for libstdc++-4.9-dev (libstdc++ of gcc 4.8 is buggy)
      - ubuntu-toolchain-r-test
      # Repo for clang-3.9
      - llvm-toolchain-trusty-3.9
    packages:
      - ninja-build

matrix:
  include:
    # Clang 3.5 with disabled c++14 support
    - install:
      - travis_retry sudo apt-get install -y libstdc++-4.9-dev
      compiler: clang
      env: CC_COMP="clang" CXX_COMP="clang++" EXTRA_OPTS="-DDRB_MAXIMUM_CXX_STANDARD=11"
    #
    # Clang 3.9 (has c++14)
    - install:
      - travis_retry sudo apt-get install -y clang-3.9 libstdc++-4.9-dev
      compiler: clang
      env: CC_COMP="clang-3.9" CXX_COMP="clang++-3.9" GCOV="llvm-cov-3.9 gcov"
    #
    # gcc-4.8 (c++11 and without tests, since rapidcheck does not compile like this)
    - compiler: gcc
      env: CC_COMP="gcc" CXX_COMP="g++" EXTRA_OPTS="-DKRIMS_ENABLE_TESTS=OFF" TESTS=0
    #
    # gcc-5 (with tests and c++14)
    - install:
      - travis_retry sudo apt-get install -y g++-5
      compiler: gcc
      env: CC_COMP="gcc-5" CXX_COMP="g++-5" GCOV="gcov-5"
    #
    # Clang-tidy 3.9
    - install:
      - travis_retry sudo apt-get install -y clang-3.9 libstdc++-4.9-dev clang-tidy-3.9
      # Install yaml for the SetupClangTargets.cmake module
      #     (which needs it for a generated python scripts)
      - travis_retry pip3 install --user pyyaml
      compiler: clang
      env: CC_COMP="clang-3.9" CXX_COMP="clang++-3.9" BUILD_TARGET="clang-tidy-krims" TESTS=0

script:
  - cmake --version
  - ninja --version
  - mkdir ${TRAVIS_BUILD_DIR}/build && cd ${TRAVIS_BUILD_DIR}/build
  - cmake -DCMAKE_CXX_COMPILER=${CXX_COMP} -DCMAKE_C_COMPILER=${CC_COMP}
           -DCMAKE_BUILD_TYPE=DebugRelease ${EXTRA_OPTS}
           -DDRB_COVERAGE_Debug=ON
           -DAUTOCHECKOUT_MISSING_REPOS=ON
           -DRC_ENABLE_TESTS=OFF
           -DKRIMS_ENABLE_EXPERIMENTAL=ON
           -GNinja ..
  - cmake --build  . --target ${BUILD_TARGET:-all} -- -j ${CORES}
  - if [ "${TESTS}" != "0" ]; then
        ctest -j ${CORES} --output-on-failure -R "$TESTS";
    else true; fi

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  - find -iname "*.gc*"
  - if [ "${GCOV}" ]; then coveralls --gcov "$GCOV"  --gcov-options '\-lp'
           --verbose
           --include src
           --root ${PWD} --build-root ${PWD}/build;
    fi
